### PR TITLE
Ensure go-plus Panel Does Not Show On Startup, If So Configured

### LINKED ISSUE #514: The Panel options are broken
The panel will be open always when I start Atom, regardless of whether I select it to be open or closed.

### PR DESCRIPTION
**Pull request by joefitzgerald**
- Fixes #514

### CODE REVIEW

File: lib/panel-manager.js [hunk 1]
```diff
@@ -12,18 +12,22 @@ class PanelManager {
     this.subscriptions = new CompositeDisposable()
     this.viewProviders = new Map()
     this.resizeSubscriptions = new CompositeDisposable()
+    this.initialized = false
     this.subscribeToConfig()
```
Comment (lloiser) [inline lib/panel-manager.js]: yet your approach feels quite solid too. Just wanted to mention the actual cause...
